import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { runCli, type CliIo } from "../src/cli.js";
import type { AuthyService } from "../src/service.js";
function output(): { io: CliIo; stdout: string[]; stderr: string[] } { const stdout: string[] = [], stderr: string[] = []; return { stdout, stderr, io: { stdout: { write: (v) => (stdout.push(v), true) }, stderr: { write: (v) => (stderr.push(v), true) } } }; }
const service: AuthyService = { login: async () => ({ accountId: "ada" }), logout: async () => ({ accountId: "ada", loggedOut: true }), listAccounts: async () => ({ accounts: [], total: 0, skip: 0, take: 25 }), getAccountSummary: async () => ({ count: 0 }), getAccountStatus: async () => ({ accountId: "ada", subscription: "active", checkedAt: "2026-01-01T00:00:00.000Z", cached: false, tokenUsage: null, rateLimits: null }), execute: async () => ({ requestId: "request", accountId: "ada", exitCode: 0, output: "" }) };
describe("authy CLI", () => {
  it("writes successful data and a human-readable JSON message to stdout", async () => { const result = output(); assert.equal(await runCli(["accounts", "list"], result.io, service), 0); assert.deepEqual(result.stderr, []); assert.deepEqual(JSON.parse(result.stdout[0]), { ok: true, message: "Accounts loaded successfully.", data: { accounts: [], total: 0, skip: 0, take: 25 } }); });
  it("formats CLI output as one JSON Lines record", async () => { const result = output(); await runCli(["accounts", "list"], result.io, service); assert.match(result.stdout[0], /^\{"ok":true,/); assert.equal(result.stdout[0].split("\n").filter(Boolean).length, 1); });
  it("renders Commander help as plain text on stdout", async () => { const result = output(); assert.equal(await runCli(["exec", "--help"], result.io, service), 0); assert.equal(result.stderr.length, 0); assert.equal(result.stdout.length, 1); assert.match(result.stdout[0], /^Usage: authy exec \[options\]/); assert.match(result.stdout[0], /Runs a Codex task/); assert.doesNotMatch(result.stdout[0], /^\{/); });
  it("explains invalid usage in English via stderr JSONL", async () => { const result = output(); assert.equal(await runCli(["exec", "--account-id", "ada"], result.io, service), 2); assert.equal(result.stdout.length, 0); const error = JSON.parse(result.stderr[0]).error; assert.equal(error.code, "INVALID_USAGE"); assert.equal(error.message, "The required option --prompt <text> is missing."); });
  it("writes typed stream events without duplicating them in the completion result", async () => { const result = output(); const streamingService: AuthyService = { ...service, execute: async (_input, onEvent) => { onEvent?.({ event: "exec.turn.started", data: { threadId: "thread_1" } }); return { requestId: "request", accountId: "ada", exitCode: 0, output: "Final answer." }; } }; assert.equal(await runCli(["exec", "--account-id", "ada", "--prompt", "test", "--detail-level", "turns"], result.io, streamingService), 0); assert.equal(result.stdout.length, 2); assert.equal(JSON.parse(result.stdout[0]).event, "exec.turn.started"); assert.deepEqual(JSON.parse(result.stdout[0]).data, { threadId: "thread_1" }); assert.deepEqual(JSON.parse(result.stdout[1]).data, { requestId: "request", accountId: "ada", exitCode: 0, output: "Final answer." }); });
  it("writes the complete execution result for end-detail execution", async () => { const result = output(); assert.equal(await runCli(["exec", "--account-id", "ada", "--prompt", "test", "--detail-level", "end"], result.io, service), 0); assert.equal(result.stdout.length, 1); assert.deepEqual(JSON.parse(result.stdout[0]).data, { requestId: "request", accountId: "ada", exitCode: 0, output: "" }); });
  it("starts the API server with the configured defaults", async () => { const result = output(); let options: unknown; assert.equal(await runCli(["serve"], result.io, service, (_service, input) => ({ listen: async () => (options = input, { host: "127.0.0.1", port: 8787 }), close: async () => undefined })), 0); assert.deepEqual(options, { host: "127.0.0.1", port: 8787 }); assert.deepEqual(JSON.parse(result.stdout[0]).data, { host: "127.0.0.1", port: 8787 }); });
  it("rejects external API bindings", async () => { const result = output(); assert.equal(await runCli(["serve", "--host", "0.0.0.0"], result.io, service), 2); assert.equal(JSON.parse(result.stderr[0]).error.code, "INVALID_USAGE"); });
});
